### ISSUE TITLE
Spanish data allowed?

### ISSUE THREAD

**Issue by johnfelipe** [alanbraz/cognitive-head-hunter#12]

**Comment by cavoto** [comment]
CHH uses the Concept Insight service from Watson and it does not support Spanish

http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/concept-insights/
https://developer.ibm.com/answers/questions/281950/how-can-i-use-spanish-in-concept-insights-1/?smartspace=watson
