### ISSUE TITLE
Migrate from MongoLab to other db

### ISSUE THREAD

**Issue by alanbraz** [alanbraz/cognitive-head-hunter#5]

**Comment by germanattanasio** [comment]
I think you can use cloudant. I have good experience using it and they have a npm module that makes things easy.

**Comment by alanbraz** [comment]
yeah, we will go to Cloudant

**Comment by cavoto** [comment]
@germanattanasio do you know if we can create an account there without a credit card ? The doc I found mentioned a credit card required

**Comment by germanattanasio** [comment]
you don't pay for it as long as you use bluemix and your ibm account.

**Comment by cavoto** [comment]
:+1:

**Comment by alanbraz** [comment]
almost done, just need to test one last method

**Comment by alanbraz** [comment]
done, migrantion of data and code completed

**Comment by alanbraz** [comment]
mongolab service removed
