### ISSUE TITLE
Job Search in Cognitive Head Hunter Sample app not working

### ISSUE THREAD

**Issue by chughts** [alanbraz/cognitive-head-hunter#7]
The Job Search component of the application as running as the sample application in the Watson Developer Cloud sample app gallery is not working. Personality Insights comes back with its graphic, but the job search portion remains spinning. 

The HR option returns 
     {"readyState":4,"responseText":"Cannot PUT /db/jobs/536319405678894c3047fbc2a9e499ad\n","status":404,"statusText":"Not Found"}

at the top of the screen.

Looks like the problem relates to creating new entries in the database. Old entries appear to be ok

**Comment by chughts** [comment]
The HR option returns 
     {"readyState":4,"responseText":"Cannot PUT /db/jobs/536319405678894c3047fbc2a9e499ad\n","status":404,"statusText":"Not Found"}

at the top of the screen.

**Comment by alanbraz** [comment]
@cavoto can you help on this too?

**Comment by alanbraz** [comment]
any clue here?

**Comment by cavoto** [comment]
@alanbraz Try to manually remove 536319405678894c3047fbc2a9e499ad from the database

**Comment by lizardcircus** [comment]
having issue with POST
{"readyState":4,"responseText":"Cannot POST /db/jobs/56c05eabc012ee5da44c8fd8df5c0cde\n","status":404,"statusText":"Not Found"}

initially created 10 candidates then started adding jobs, after the 6th job the error message appears.

**Comment by alanbraz** [comment]
this is a sync problem between the db and the service corpus :(
